# Generated by Django 5.0 on 2024-09-22 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequestpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
