# Generated by Django 5.0 on 2024-09-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodology', '0004_profile_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Edhi', max_length=70),
        ),
    ]
