# Generated by Django 5.0 on 2024-10-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodology', '0006_alter_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
