# Generated by Django 5.0 on 2024-10-01 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodology', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
