# Generated by Django 5.0 on 2024-10-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodology', '0010_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='blood_gorup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
    ]
