# Generated by Django 5.0 on 2024-10-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodology', '0012_rename_user_profile_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blood_gorup',
            field=models.CharField(max_length=5),
        ),
    ]
