# Generated by Django 5.0 on 2024-10-05 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodology', '0017_bloodrequestpost_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestpost',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bloodology.userprofile'),
            preserve_default=False,
        ),
    ]
