# Generated by Django 5.0 on 2024-10-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodology', '0018_alter_bloodrequestpost_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
