# Generated by Django 5.0 on 2024-10-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodology', '0019_userprofile_latitude_userprofile_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
    ]
